<?php

namespace Geograph\ProgdechBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacRepository extends EntityRepository
{
    /**
     * Retourne le nombre de bacs pour un point de collecte
     * 
     * @return type
     */
    public function getCountBacsPointCollecte($id_pointcollecte)
    {
        return $this->createQueryBuilder('l')
                        ->select('COUNT(l)')
                        ->getQuery() 
                        ->getSingleScalarResult(); 
    }
}
