<?php

namespace Geograph\ProgdechBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneRepository extends EntityRepository
{
    public function getSelectList(){
        $qb = $this->createQueryBuilder('c')
                ->orderBy('c.nom');
        return $qb;
    }
}
