<?php

namespace Geograph\ProgdechBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FondscarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FondscarteRepository extends EntityRepository
{
}
