<?php

namespace Geograph\ProgdechBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypefluxRepository extends EntityRepository
{    
    /**
     * Retourne le nombre de bacs pour un point de collecte
     * 
     * @return type
     */
    public function getTypeFluxDistinctCommune($id_commune)
    {
        $query = $this->_em->createQuery('
                SELECT distinct tf
                FROM GeographProgdechBundle:Typeflux tf
                JOIN tf.modelesbac mb
                JOIN mb.bacs b
                JOIN b.pointcollecte pc
                JOIN pc.commune c
                WHERE c.id = ?1')
                ->setParameter(1, $id_commune)
            ;
        
        $result = $query->getResult();
        
        return $result;
    }
}
