ALTER TABLE t_collectes DROP id_bac;
ALTER TABLE t_collectes DROP id_user;
DROP INDEX t_criteres_nom_critere_key;
ALTER TABLE t_donneescollectes DROP CONSTRAINT fk_t_donneescollectes_id_user;
DROP INDEX IDX_48ED2E616B3CA4B;
ALTER TABLE t_donneescollectes DROP id_user;
ALTER TABLE t_fondscarte ADD nom_fondcarte VARCHAR(50) NOT NULL;
ALTER TABLE t_fondscarte DROP nom_foncarte;
ALTER TABLE t_fondscarte ALTER id_fondcarte DROP DEFAULT;
ALTER TABLE t_fondscarte ALTER attribution_fondcarte SET NOT NULL;
ALTER TABLE t_fondscarte ALTER attribution_fondcarte TYPE VARCHAR(255);
ALTER TABLE t_fondscarte ALTER minzoom_fondcarte SET NOT NULL;
ALTER TABLE t_fondscarte ALTER maxzoom_fondcarte SET NOT NULL;
ALTER TABLE t_fondscarte ALTER id_typefondcarte DROP NOT NULL;
ALTER TABLE t_fondscarte ADD CONSTRAINT FK_A324C2B4A9B69F7A FOREIGN KEY (id_typefondcarte) REFERENCES t_typesfondscartes (id_typefondcarte) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX IDX_A324C2B4A9B69F7A ON t_fondscarte (id_typefondcarte);
ALTER TABLE t_ptscollecte DROP CONSTRAINT fk_t_ptscollecte_id_photo;
DROP INDEX IDX_C3F488B8FA32C528;
ALTER TABLE t_ptscollecte DROP id_photo;
ALTER TABLE t_tournees DROP CONSTRAINT fk_t_tournees_id_user;
DROP INDEX IDX_78B979176B3CA4B;
ALTER TABLE t_tournees DROP id_user;
ALTER TABLE t_typesfondscartes ALTER id_typefondcarte DROP DEFAULT;
