CREATE SEQUENCE t_constats_id_constat_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE t_critereconstats_id_critere_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE t_critereobservations_id_critere_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE t_donneescollectes_id_donneecollecte_seq INCREMENT BY 1 MINVALUE 1 START 1;
ALTER TABLE t_communes DROP geom_com;
ALTER TABLE t_communes ALTER id_com DROP DEFAULT;
ALTER TABLE t_ptscollecte ALTER id_ptcollecte DROP DEFAULT;
ALTER TABLE t_bacs ALTER id_bac DROP DEFAULT;
ALTER TABLE t_collectes ALTER id_collecte DROP DEFAULT;
ALTER TABLE t_constats ALTER id_constat DROP DEFAULT;
ALTER TABLE t_critereconstats ALTER id_critere DROP DEFAULT;
ALTER TABLE t_critereobservations ALTER id_critere DROP DEFAULT;
ALTER TABLE t_depart ALTER id_depart DROP DEFAULT;
ALTER TABLE t_formats ALTER id_format DROP DEFAULT;
ALTER TABLE t_jours ALTER id_jour DROP DEFAULT;
ALTER TABLE t_jours ALTER nom_jour TYPE VARCHAR(8);
ALTER TABLE t_modelesbacs ALTER id_modelebac DROP DEFAULT;
ALTER TABLE t_modelesbacs ALTER id_typeflux DROP NOT NULL;
ALTER TABLE t_observations ALTER id_observation DROP DEFAULT;
ALTER TABLE t_ouvertures ALTER id_ouverture DROP DEFAULT;
ALTER TABLE t_photos ALTER id_photo DROP DEFAULT;
ALTER TABLE t_populations ALTER id_population DROP DEFAULT;
ALTER TABLE t_populations ALTER id_com DROP NOT NULL;
ALTER TABLE t_tournees ALTER id_tournee DROP DEFAULT;
ALTER TABLE t_typeflux ALTER id_typeflux DROP DEFAULT;
ALTER TABLE t_users ALTER id_user DROP DEFAULT;
