# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    geometrie_carte:
        class: Geograph\ProgdechBundle\Geometrie\CarteDAO
    geometrie_marker:
        class: Geograph\ProgdechBundle\Geometrie\MarkerDAO
        arguments: [ "%kernel.root_dir%" ]
    geograph_progdech:
        class: Geograph\ProgdechBundle\Progdech\Progdech
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
